export const HomeFeaturesData = [
  {
    id: 1,
    img: "/home/1Communicate.svg",
    heading: "communicate with Confidence",
    titleWhite: "Ai",
    titleBrown: "Language Training",
    description:
      "Unlock the power of clear, confident communication with milgpt – your AI-powered language training partner. Whether you’re preparing for professional presentations, interviews, or everyday conversations, milgpt helps you refine your speaking, improve fluency, and build confidence in any language. Learn smarter, practice naturally, and speak with impact.",
    features: [
      "Learn foreign languages fast",
      "Role-based simulations (checkpoint, intel gathering, etc.)",
      "Built-in pronunciation and accent feedback",
      "Voice-enabled interactive dialogues",
      "Personalized by role, region, and rank",
    ],
    buttonText: "Start Training Now",
  },

  {
    id: 2,
    img: "/home/2Protocol.svg",
    heading: " KNOW THE PROTOCOL — INSTANTLY",
    titleWhite: "SOP and Document",
    titleBrown: "Chat Assistant",
    description:
      "Stay compliant and efficient with milgpt – your AI-powered SOP and Document Chat Assistant. Access critical protocols instantly, simplify complex procedures, and ensure accuracy in every step. From SOP lookups to document guidance, milgpt helps you save time, reduce errors, and always stay on protocol.",
    features: [
      "Search hundreds of SOPs and manuals instantly",
      "Supports PDF, DOCX, and structured data",
      "Accurate retrieval of mission-critical details",
      " Perfect for training, briefings, and on-field decisions",
      "24/7 knowledge — no scrolling required",
    ],
    buttonText: "Access SOP Now",
  },

  {
    id: 3,
    img: "/home/3Briefed.svg",
    heading: "STAY BRIEFED. STAY AHEAD.",
    titleWhite: "Top Military News",
    titleBrown: "Aggregator",
    description:
      "Stay mission-ready with the top military news aggregator powered by milgpt. Get real-time updates, critical briefings, and global defense insights — all in one place. From breaking headlines to in-depth analysis, never miss what matters in the world of security and strategy.",
    features: [
      "Mobile & command center ready",
      "Real-time defense news from global sources",
      "Situational awareness dashboards",
      "Filter by country, keyword, or force type",
      " Categorized by region (e.g., Europe, Indo-Pacific) or domain (air, land, cyber)",
    ],
    buttonText: "Read Military News",
  },

  {
    id: 4,
    img: "/home/4RawData.svg",
    heading: " RAW DATA TO REAL INTEL",
    titleWhite: "AI Report Intelligence",
    titleBrown: "Report Generator",
    description:
      "Transform overwhelming data into actionable intelligence with milgpt’s AI-powered Report Generator. From raw inputs to polished, professional intelligence reports, get accurate insights, structured analysis, and clear recommendations — instantly. Stay informed, stay decisive.",
    features: [
      "Export to PDF or encrypted formats",
      "Reduces human analysis time by 80%",
      " Auto-generates visual highlights and key insights",
      " Integrates drone, satellite, and comms data",
      "Ideal for briefing commanders and field agents",
    ],
    buttonText: "Generate Report",
  },

  {
    id: 5,
    img: "/home/5Operate.svg",
    heading: "OPERATE SMARTER, FASTER",
    titleWhite: "Military Info",
    titleBrown: "Chat Bot",
    description:
      "Boost decision-making and efficiency with milgpt – the Military Info Chat Bot. Get instant answers to mission-critical questions, streamline knowledge access, and operate with confidence. From protocols to tactical insights, milgpt helps you stay sharp, smart, and always ahead.",
    features: [
      "Real-time answers to military queries",
      " Covers tactics, gear, SOPs & chains of command",
      "Voice and text chat options",
      " AI-curated reliable sources",
      "Built for field use & training environments",
    ],

    buttonText: "Start Chatting",
  },
];

export const HomeFaqsData = [
  {
    id: 1,
    question: "What is Imagine?",
    answer: "What is Imagine?",
  },
  {
    id: 2,
    question:
      "Can I use the images generated by the platform for commercial purposes?",
    answer:
      "Can I use the images generated by the platform for commercial purposes?",
  },
  {
    id: 3,
    question: "What payment options are available?",
    answer: "What payment options are available?",
  },
  {
    id: 4,
    question: "Is there a free trial?",
    answer: "Is there a free trial?",
  },
  {
    id: 5,
    question: "Can I cancel my Plan?",
    answer: "Can I cancel my Plan?",
  },
  {
    id: 6,
    question: "Can I upgrade or downgrade my current plan?",
    answer: "Can I upgrade or downgrade my current plan?",
  },
  {
    id: 7,
    question: "What is Imagine's refund policy?",
    answer: "What is Imagine's refund policy?",
  },
];

// Pricing section data

export const HomepricingPlansData = [
  {
    id: 1,

    title: "Basic",
    priceMonthlyUSD: "$4.99",
    priceYearlyUSD: "$15.99",
    description:
      "Perfect for starters—get essential features to kickstart your AI journey.",
    features: [
      "10000 Content Words",
      "No Free Images",
      "LLM Models Integration",
      "10 Chats Prompts",
      "Voice Over Limited Words",
      "No Keyword Research",
      "10 One Click Blog Creation",
      "No Simultaneous Users",
    ],
  },
  {
    id: 2,
    title: "StanDARD",
    priceMonthlyUSD: "$24.99",
    priceYearlyUSD: "$79.99",
    description:
      "Unlock advanced tools for growing needs and higher productivity.",
    features: [
      "150000 Content Words",
      "500 Free Images",
      "LLM Models Integration",
      "5000 Chats Prompts",
      "Voice Over Limited Words",
      "Keyword Research Unlimited",
      "50 One Click Blog Creation",
      "WordPress Integration",
      "1 WordPress Site Allowed",
      "2 Simultaneous Users",
    ],
    isFeatured: true,
  },
  {
    id: 3,
    title: "Premium",
    priceMonthlyUSD: "$499.99",
    priceYearlyUSD: "$1599.99",
    description:
      "The ultimate package with full access and priority support for professionals.",
    features: [
      "Unlimited Content Words",
      "Unlimited Free Images",
      "LLM Models Integration",
      "Unlimited Chats Prompts",
      "Voice Over Unlimited Words",
      "Keyword Research Unlimited",
      "Unlimited One Click Blog Creation",
      "WordPress Integration",
      "1k WordPress Blog Automation",
      "1 WordPress Site Allowed",
      "4 Simultaneous Users",
    ],
  },
];

export const HometestimonialData = [
  {
    id: 1,
    quote:
      "Integrating AI into our defense systems revolutionized battlefield awareness. We can now anticipate threats and respond in real time with unmatched precision.",
    author: "Lt. Cheryl Butler, Strategic Operations Lead",
    backgroundColor: "#6B946A",
    image: "/home/GridBg1.svg",
  },
  {
    id: 2,
    quote:
      "Thanks to AI-assisted war gaming, our teams simulate thousands of scenarios in minutes—sharpening strategies before deployment ever begins.",
    author: "Rita Eland, Defense Analyst",
    backgroundColor: "#DCD194",
    image: "/home/GridBg2.svg",
  },
  {
    id: 3,
    quote:
      "Decision-making in high-pressure environments has never been this effective. AI provides fast, data-driven insights that save lives on and off the field.",
    author: "Col. Ted Ortega, Tactical AI Unit",
    backgroundColor: "#3A3E4B",
    image: "/home/GridBg3.svg",
  },
  {
    id: 4,
    quote:
      "From logistics to surveillance, AI enhances every layer of military readiness. It’s not just support—it’s a strategic partner.",
    author: "Kayla Wheatly, Military Innovation Officer",
    backgroundColor: "#5B4C3E",
    image: "/home/GridBg4.svg",
  },
];
